### PR TITLE
Use UTC everywhere

### PR DESCRIPTION
**Pull request by wimleers**
Solves #24.

### CODE REVIEW

**Comment by curzon01** [comment]
Using UTC for MySQL as input with data type `timestamp` does not work. MySQL assumes that a value for `timestamp`is in local time, even if the date is already in UTC. What goes wrong with UTC as a basis is converted back during readout. If we use UTC for inputs on MySQL, the data type should be `datetime`.
With Sqlite it seems to be different, there the data type `timestamp` is considered as UTC, it must be checked.

The reason why I transfer the timestamp from the program in Sqlite is that I didn't want to have different times for INSERT and the subsequent UPDATE, but the timestamp that is generated centrally in one place in the program. BTW: MySQL doesn't really need the transfer either, it can generate it itself.

Thanks for the suggestion, I just need to complete and test it.

**Review by curzon01 — APPROVED** [review]

**Review by curzon01 — CHANGES_REQUESTED** [review]
should be kept as is to keep the same ts for boath ops

**Comment by wimleers** [comment]
> With Sqlite it seems to be different, there the data type timestamp is considered as UTC
I'm using this with SQLite in particular, and I can confirm this is _definitely_ the case for SQLite. Weird that MySQL went for such a poor default 🤯 

> it must be checked.

You can check it like this:
```
$ sqlite3 tstest < sqlite.sql
$ sqlite3 tstest "INSERT INTO mqtt (topic, value, qos, retain) VALUES('foobar', 'baz', 0, 0);"
$ sqlite3 tstest "SELECT * FROM mqtt;"
1|2023-11-05 11:24:07|foobar|baz|0|0|1|1
$ date
Sun Nov  5 12:25:00 CET 2023
$ TZ=UTC date
Sun Nov  5 11:25:06 UTC 2023
```

>  but the timestamp that is generated centrally in one place in the program.

This I definitely understand 👍

**Comment by wimleers** [comment]
Feedback addressed 👍 This is now a one-line PR 😄

**Comment by curzon01** [comment]
> Weird that MySQL went for such a poor default

this is a misunderstanding:
There is no default data type for date and time in MySQL, there exists (compared to SQlite) two data types for date and time: `TIMESTAMP` and `DATETIME`.
You (and no none-existing default) just have to choose the right one for your tables. To store UTC converted data values you should use `DATETIME` and not `TIMESTAMP` (as I did for my locale times) and for local value it's better to use `TIMESTAMP`

So you want to use UTC input values from .py, you have to change `DATETIME` for columns `ts` in MySQL too:

change 
```SQL
`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
```
to
```SQL
`ts` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
```

**Comment by curzon01** [comment]
> So you want to use UTC input values from .py, you have to change `DATETIME` for columns `ts` in MySQL too:

Also note that the underlying environment for SQlite is your operating system, for MySQL it is the settings of your MySQL server (not server OS alone), i.e. your test with SQlite above (the server should insert the timestamp itself) might work or not under MySQL, where the conditions for automatic insertion of timestamps by the server are somewhat more complicated.

**Comment by curzon01** [comment]
pls make the related changes for MySQL as described above (I have no idea how to add an additional file modification to this PR)

**Review by curzon01 — APPROVED** [review]

**Review by curzon01 — CHANGES_REQUESTED** [review]
pls make the related changes for MySQL too as described above (I have no idea how to add an additional file modification to this PR)

**Comment by curzon01** [comment]
adapt my own changes

**Pull request closed without merging**
